import type { Locale } from "./types";

type Params = Record<string, string | number | null | undefined>;

const en = {
  language:"Language", mainNavigation:"Main navigation", researchDesk:"Research desk", model:"Model", holdingPeriod:"2–12 week swing", dataStatus:"Data status",
  dashboard:"Overview", scanner:"Market scanner", signals:"Signals", security:"Security research",
  refreshQuotes:"Update latest quotes", refreshingQuotes:"Updating quotes {processed}/{total}", refreshComplete:"Updated {updated} quotes directly from the public market source ({failed} failed); model scores remain from the latest full analysis.", refreshFailed:"The server could not refresh public market quotes.",
  fullAnalysis:"Run full analysis", fullAnalysisConfirmTitle:"Confirm full analysis", fullAnalysisConfirmBody:"The cloud model will refresh historical price-volume data and recalculate scores, confidence and trade plans. Public data always remains SHADOW.", analysisScope:"Analysis scope", analysisEstimate:"Estimated universe", analysisFirstBackfill:"History mode", analysisFirstBackfillValue:"Five-year backfill when no cloud artifact exists; otherwise a seven-day overlap update", cancel:"Cancel", startAnalysis:"Start analysis", analysisQueued:"Cloud analysis queued", analysisActive:"Full analysis in progress", analysisProgress:"{completed}/{total} buckets complete", analysisJobCount:"{count} recent analysis jobs", analysisCloudMissing:"Cloud analysis is not configured. Connect the public GitHub repository, workflow token and Secrets first.", analysisStarted:"Full analysis started. Progress will remain available after refresh or sign-in.", analysisComplete:"Full analysis completed and passing buckets were activated.", analysisPartial:"Analysis partially completed; successful buckets were activated and failed buckets kept their previous results.", analysisFailed:"Full analysis failed; no incomplete result was activated.", analysisStalled:"Analysis heartbeat stopped. The work lock was released and the analysis can be retried.", phaseQueued:"Queued", phaseDiscovery:"Discovering securities", phaseHistory:"Updating five-year history", phaseEnrichment:"Enriching classifications", phaseScoring:"Scoring and applying gates", phaseUploading:"Uploading and activating", phaseComplete:"Complete", analysisTime:"Model analysis time", quoteTime:"Latest quote time", analysisPrice:"Analysis price", reanalysisRequired:"Full analysis required", reanalysisBuyBlocked:"The latest quote is outside the original entry zone. A new paper BUY is blocked until full analysis recalculates the trade plan.",
  modelTrack:"Model track", activeModel:"Current v2.0", candidateModel:"Market profiles v2.2", candidateLocked:"v2.2 uses a separate profile for every market and asset type. Each bucket remains SHADOW until provisional backtesting and 30 trading-day validation pass.", entryQuality:"Entry quality", high52Distance:"Distance from 52-week high", high5yDistance:"Distance from five-year high", extensionAtr:"Distance from SMA20", breakoutLevel:"Breakout level", volumeRatio:"Volume / 20-day median", closeLocation:"Close location", marketRegime:"Market regime", marketBreadth:"Above SMA50 breadth", plannedR:"Planned R multiples", chart5y:"Five-year price and entry map", candidatePaperLocked:"This v2.2 market profile is not yet ACTIVE_SHADOW, so paper BUY is locked.", candidateAwaiting:"Run full analysis to create v2.2 market-profile results for this scope.",modelProfile:"Market model profile",strategyFamily:"Strategy family",gatePreset:"Gate preset",profileStatus:"Profile validation",profileCalibrating:"Calibrating",profileBacktestPassed:"Backtest passed",profileShadowValidating:"30-day shadow validation",profileActiveShadow:"Active shadow",profileRejected:"Rejected",
  fullScan:"Full scan", discovered:"Discovered", analyzed:"Analyzed", failed:"Failed", fallback:"Fallback", running:"Running", universeTarget:"500 stocks + 100 ETFs per market",
  shadowBuy:"Shadow buy", watch:"Watch", hardGated:"Hard gated", ibkrFeed:"IBKR feed", off:"Off", ranked:"ranked", limited:"limited",
  stock:"Stock", etf:"ETF", buy:"Buy", hold:"Hold", reduce:"Reduce", exit:"Exit", shadow:"Shadow", formal:"Formal",
  realtime:"Real-time", delayed:"Delayed", fallbackData:"Fallback", stale:"Stale",
  trendConfirmed:"Trend confirmed", trendUnconfirmed:"Trend not confirmed", momentumLeadership:"Momentum leadership", momentumMixed:"Mixed momentum", riskControlled:"Risk controlled", volatilityElevated:"Elevated volatility", liquidityAcceptable:"Liquidity acceptable", liquidityThin:"Thin liquidity", formalGateActive:"Formal gate active", ibkrNotConnected:"IBKR not connected",
  insufficientHistory:"Insufficient history", staleData:"Stale data", sourceWarning:"Source warning", invalidPrice:"Invalid price",
  portfolioEyebrow:"Paper / Portfolio", loading:"Loading…", setupButton:"Set up", symbol:"Symbol", market:"Market", quantity:"Quantity", sellable:"Sellable", averagePrice:"Average / Price", baseValue:"Base value", pnl:"P&L", sell:"Paper sell", positions:"Positions", equity:"Equity", cash:"Cash", unrealizedPnl:"Unrealized P&L", drawdown:"Drawdown", feeNotice:"Fees, taxes and FX are revalidated server-side",
  refreshPositions:"Refresh holding quotes", refreshingPositions:"Refreshing holdings…", portfolioQuotesUpdated:"Updated {updated} holding quotes ({failed} failed).", quoteData:"Quote source / time", errorQuoteRefresh:"Holding quotes could not be refreshed.",
  holdingAdvice:"Holding guidance", holdingAdviceNote:"Quote refresh recalculates price triggers and portfolio exposure only. Scores and trade plans change only after full analysis.", latestQuote:"Latest quote", analysisSnapshot:"Model snapshot", costCurrent:"Cost / current", holdingReturn:"Return", portfolioWeights:"Position / market / sector", scoreConfidence:"Score / confidence", tradeGuardrails:"Stop / targets", suggestedAction:"Suggested action", recommendedSell:"Suggested sell quantity", useSuggestion:"Use suggestion", noSellable:"No quantity is currently sellable", newBuysPaused:"New paper buys are paused by the portfolio drawdown breaker.", analysisUnavailable:"No current v2 analysis is available; refresh quotes and run full analysis.", holdingDisclaimer:"Rule-based paper guidance, not a promise of return. Review the evidence before acting.",
  riskLimits:"Risk limits", riskPlan:"Risk plan", singleTradeRisk:"Risk per trade", maxPosition:"Max single position", maxSector:"Max sector", maxMarket:"Max market", drawdownBreaker:"Drawdown breaker", capitalFirst:"Capital first", balanced:"Balanced growth", growth:"Aggressive growth", minimumLotRule:"The first minimum board lot may exceed position, sector and market exposure limits, but never stop-risk, drawdown, signal, quote or cash gates.", minimumLotException:"Minimum tradable lot exception",investmentMarkets:"Enabled investment markets",investmentMarketsNote:"All seven markets remain visible for research; paper BUY is allowed only in selected markets.",customRiskPolicy:"Custom risk policy",resetRiskTemplate:"Reset to plan template",allowMinimumLot:"Allow audited first-board-lot exception",marketLimit:"{market} market limit",effectiveLimit:"Effective limit",riskPolicyPreview:"Effective preview: {position}% per security, {sector}% per sector; selected market limits total {marketTotal}%, with at least {cash}% intentionally left as cash when the total is below 100%.",riskPolicyConflictPreview:"Conflict: the security limit must stay within the allowed range and cannot exceed the sector or any selected-market limit.",
  marketRules:"Market rules", settlement:"Settlement", tradingUnit:"Trading unit", variable:"Security-specific", sessionOpen:"Open estimate", sessionClosed:"Closed estimate", ruleVersion:"Rule version",
  orderHistory:"Order history", orderTime:"Time", side:"Side", filledPrice:"Filled price", feesTaxes:"Fees + taxes", realizedPnl:"Realized P&L", status:"Status", filled:"Filled", noRecords:"No records", sellCompleted:"Paper sell completed",
  backtestEyebrow:"Model / Validation", formalLocked:"Formal signals locked", validationRequired:"Backtest and 30 trading-day shadow validation are required.", minimumTrades:"Minimum trades", profitFactor:"Profit factor", sharpe:"Sharpe", shadowDays:"Shadow days", pending:"Pending", passed:"Passed", locked:"Locked",
  notStarted:"Not started", inProgress:"In progress", migrationPending:"Migration pending", complete:"Complete", partial:"Partial",
  healthEyebrow:"System / Health", primaryFeed:"Primary real-time feed", shadowUntilValidated:"Public-source candidates remain shadow signals until IBKR subscriptions and validation are complete.", noSnapshot:"No snapshot", healthy:"Healthy", degraded:"Degraded", unavailable:"Unavailable", operational:"Operational", waiting:"Waiting for data", daily:"Daily", unknown:"Unknown",
  settingsEyebrow:"Owner / Settings", baseCurrency:"Base currency", paperCapital:"Paper capital", email:"Email", enableEmail:"Enable Email alerts through Resend", saved:"Saved", saveFailed:"Save failed", capitalSynced:"Saved: paper capital {capital}; cash adjusted by {delta}.", inAppEmailDelivered:"In-app and Email delivered", inAppDelivered:"In-app delivered; Email is not configured", alertFailed:"Alert failed",riskPolicySaved:"Risk policy saved and applied to new paper buys.",
  errorGeneric:"The request could not be completed. Please try again.", errorSignIn:"Sign in is required.", errorService:"The portfolio service is temporarily unavailable.", errorInvalidOrder:"Please provide a valid security, side and whole-number quantity.", errorSetup:"Complete portfolio setup before paper trading.", errorNoQuote:"No current quote is available for this security.", errorMarketQuantity:"The quantity does not satisfy this market's trading-unit rules.", errorStaleQuote:"The quote is stale, so simulated execution is blocked.", errorReanalysisRequired:"The latest quote is outside the analysis entry zone. Run full analysis before a new paper BUY.", errorDrawdown:"Portfolio drawdown reached the {max}% breaker; new buys are paused.", errorT1:"The sell quantity exceeds the currently sellable A-share position (T+1).", errorPosition:"This order would exceed the {max}% maximum single-position limit of the {plan} plan.", errorMarket:"This order would exceed the {max}% maximum market exposure.", errorSector:"This order would exceed the {max}% maximum sector exposure.", errorMarketDisabled:"Paper BUY is disabled for {market}. Enable it in Settings first.",errorTradeRisk:"Loss at the analyzed stop is {riskPct}%, above the {max}% limit. Maximum quantity: {maximumQuantity}; estimated minimum capital: {minimumCapital}.",errorRiskPolicy:"The custom risk policy is invalid: {rule}.",errorCash:"Insufficient paper cash after FX and transaction costs.", errorPortfolio:"The paper portfolio is temporarily unavailable.", errorOrder:"The paper order could not be completed.", errorCapitalRequired:"Paper capital must be greater than zero.", errorCapitalReduction:"Capital cannot be reduced below {minimum} while current holdings remain. Sell positions first.", errorCurrencyLocked:"Base currency is locked to {currency} after paper activity exists.", errorSettings:"Settings could not be saved.",
} as const;

type CopyKey = keyof typeof en;

const zhCN: Record<CopyKey,string> = {
  language:"语言",mainNavigation:"主导航",researchDesk:"研究工作台",model:"模型",holdingPeriod:"2–12 周波段",dataStatus:"数据状态",
  dashboard:"总览",scanner:"市场扫描",signals:"信号中心",security:"证券研究",
  refreshQuotes:"更新最新行情",refreshingQuotes:"正在更新行情 {processed}/{total}",refreshComplete:"已从公开市场来源直接更新 {updated} 条行情（{failed} 条失败）；模型分数仍来自最近一次完整分析。",refreshFailed:"服务器未能刷新公开市场行情。",
  fullAnalysis:"执行完整分析",fullAnalysisConfirmTitle:"确认完整分析",fullAnalysisConfirmBody:"云端模型会重新获取历史量价，并计算评分、信心和交易计划。公开数据始终只产生 SHADOW 信号。",analysisScope:"分析范围",analysisEstimate:"预计标的",analysisFirstBackfill:"历史模式",analysisFirstBackfillValue:"若无云端历史产物则回填五年；否则采用七日重叠增量更新",cancel:"取消",startAnalysis:"开始分析",analysisQueued:"云端分析已排队",analysisActive:"完整分析进行中",analysisProgress:"已完成 {completed}/{total} 个市场资产桶",analysisJobCount:"最近 {count} 个分析任务",analysisCloudMissing:"云端分析尚未设置。请先连接公开 GitHub 仓库、工作流 Token 和 Secrets。",analysisStarted:"完整分析已启动，刷新页面或重新登录后仍可继续查看进度。",analysisComplete:"完整分析已完成，达标的市场资产桶已启用。",analysisPartial:"部分分析完成；成功桶已启用，失败桶继续沿用旧结果。",analysisFailed:"完整分析失败；未启用任何不完整结果。",analysisStalled:"分析心跳中断；工作锁已释放，可以重新执行。",phaseQueued:"排队中",phaseDiscovery:"发现证券",phaseHistory:"更新五年历史",phaseEnrichment:"补充分类资料",phaseScoring:"评分与门槛判断",phaseUploading:"上传并启用",phaseComplete:"完成",analysisTime:"模型分析时间",quoteTime:"最新行情时间",analysisPrice:"分析时价格",reanalysisRequired:"需要完整分析",reanalysisBuyBlocked:"最新价格已离开原进场区。完整分析重新计算交易计划前，禁止新的模拟买入。",
  modelTrack:"模型版本",activeModel:"当前 v2.0",candidateModel:"分市场模型 v2.2",candidateLocked:"v2.2 为每个市场和资产类型使用独立配置；各桶通过暂定回测和 30 个交易日验证前始终保持 SHADOW。",entryQuality:"进场质量",high52Distance:"距离 52 周高点",high5yDistance:"距离五年高点",extensionAtr:"距离 SMA20",breakoutLevel:"突破位",volumeRatio:"成交量／20 日中位量",closeLocation:"收盘位置",marketRegime:"市场状态",marketBreadth:"站上 SMA50 比例",plannedR:"计划 R 倍数",chart5y:"五年价格与进场图",candidatePaperLocked:"该 v2.2 市场配置尚未达到 ACTIVE_SHADOW，禁止模拟买入。",candidateAwaiting:"请执行完整分析，为当前范围生成 v2.2 分市场结果。",modelProfile:"市场模型配置",strategyFamily:"策略族",gatePreset:"门槛配置",profileStatus:"配置验证状态",profileCalibrating:"校准中",profileBacktestPassed:"回测已通过",profileShadowValidating:"30 日影子验证",profileActiveShadow:"已启用影子配置",profileRejected:"未通过",
  fullScan:"全市场扫描",discovered:"发现标的",analyzed:"完成分析",failed:"分析失败",fallback:"备用来源",running:"运行中",universeTarget:"每个市场 500 只股票 + 100 只 ETF",
  shadowBuy:"影子买入",watch:"观察",hardGated:"风险门槛阻止",ibkrFeed:"IBKR 行情",off:"未启用",ranked:"只已排名",limited:"有限样本",
  stock:"股票",etf:"ETF",buy:"买入",hold:"持有",reduce:"减仓",exit:"退出",shadow:"影子",formal:"正式",
  realtime:"实时",delayed:"延迟",fallbackData:"备用来源",stale:"过期",
  trendConfirmed:"趋势确认",trendUnconfirmed:"趋势未确认",momentumLeadership:"动量领先",momentumMixed:"动量混合",riskControlled:"风险受控",volatilityElevated:"波动率偏高",liquidityAcceptable:"流动性合格",liquidityThin:"流动性不足",formalGateActive:"正式门槛已启用",ibkrNotConnected:"IBKR 尚未连接",
  insufficientHistory:"历史数据不足",staleData:"数据已过期",sourceWarning:"数据源警告",invalidPrice:"价格无效",
  portfolioEyebrow:"模拟交易／投资组合",loading:"加载中…",setupButton:"前往设置",symbol:"证券代码",market:"市场",quantity:"数量",sellable:"可卖",averagePrice:"成本／现价",baseValue:"基准币值",pnl:"损益",sell:"模拟卖出",positions:"持仓",equity:"净值",cash:"现金",unrealizedPnl:"未实现损益",drawdown:"回撤",feeNotice:"费用、税费与汇率会在服务器重新计算",
  refreshPositions:"更新持仓行情",refreshingPositions:"正在更新持仓行情…",portfolioQuotesUpdated:"已更新 {updated} 条持仓行情（{failed} 条失败）。",quoteData:"行情来源／时间",errorQuoteRefresh:"未能更新持仓行情。",
  holdingAdvice:"持仓投资建议",holdingAdviceNote:"更新行情只会重算价格触发条件和组合敞口；评分与交易计划仅在完整分析后更新。",latestQuote:"最新行情",analysisSnapshot:"模型分析快照",costCurrent:"成本／现价",holdingReturn:"持仓收益率",portfolioWeights:"单股／市场／行业占比",scoreConfidence:"评分／信心",tradeGuardrails:"止损／目标",suggestedAction:"建议操作",recommendedSell:"建议卖出数量",useSuggestion:"采用建议",noSellable:"当前没有可卖数量",newBuysPaused:"组合回撤已触发熔断，暂停新的模拟买入。",analysisUnavailable:"没有可用的当前 v2 分析；请先更新行情并执行完整分析。",holdingDisclaimer:"这是基于规则的模拟持仓建议，不承诺收益；操作前请核对判断依据。",
  riskLimits:"风险限制",riskPlan:"风险计划",singleTradeRisk:"单笔风险",maxPosition:"单只证券上限",maxSector:"单一行业上限",maxMarket:"单一市场上限",drawdownBreaker:"回撤熔断线",capitalFirst:"保本优先",balanced:"均衡成长",growth:"积极成长",minimumLotRule:"首次最小整手可突破单股、行业及市场敞口上限，但绝不放宽止损风险、回撤、信号、行情和现金门槛。",minimumLotException:"最小交易整手例外",investmentMarkets:"允许投资的市场",investmentMarketsNote:"七个市场仍全部展示研究结果；只有选中的市场允许模拟买入。",customRiskPolicy:"自定义风险政策",resetRiskTemplate:"恢复计划模板",allowMinimumLot:"允许可审计的首次整手例外",marketLimit:"{market} 市场上限",effectiveLimit:"实际生效上限",riskPolicyPreview:"生效预览：单只证券 {position}%，单一行业 {sector}%；已选市场上限合计 {marketTotal}%，合计低于 100% 时至少刻意保留 {cash}% 现金。",riskPolicyConflictPreview:"限制存在矛盾：单只证券上限必须在允许范围内，且不得高于行业上限或任何已选市场上限。",
  marketRules:"市场规则",settlement:"交收",tradingUnit:"交易单位",variable:"按证券而定",sessionOpen:"预计开市",sessionClosed:"预计休市",ruleVersion:"规则版本",
  orderHistory:"订单记录",orderTime:"时间",side:"方向",filledPrice:"成交价",feesTaxes:"费用与税费",realizedPnl:"已实现损益",status:"状态",filled:"已成交",noRecords:"暂无记录",sellCompleted:"模拟卖出完成",
  backtestEyebrow:"模型／验证",formalLocked:"正式信号尚未解锁",validationRequired:"必须通过回测及 30 个交易日影子验证。",minimumTrades:"最低交易笔数",profitFactor:"获利因子",sharpe:"夏普比率",shadowDays:"影子验证天数",pending:"待验证",passed:"已通过",locked:"未解锁",
  notStarted:"尚未开始",inProgress:"进行中",migrationPending:"迁移待完成",complete:"完成",partial:"部分完成",
  healthEyebrow:"系统／数据健康",primaryFeed:"正式实时主行情",shadowUntilValidated:"完成 IBKR 行情订阅及验证前，公开来源候选仍只显示影子信号。",noSnapshot:"暂无快照",healthy:"正常",degraded:"降级",unavailable:"不可用",operational:"运行正常",waiting:"等待数据",daily:"日线",unknown:"未知",
  settingsEyebrow:"仅限拥有者／设置",baseCurrency:"基准货币",paperCapital:"模拟资金",email:"电子邮箱",enableEmail:"通过 Resend 启用邮件提醒",saved:"已保存",saveFailed:"保存失败",capitalSynced:"已保存：模拟本金 {capital}；现金同步调整 {delta}。",inAppEmailDelivered:"站内和邮件通知均已送达",inAppDelivered:"站内通知已送达；邮件尚未配置",alertFailed:"通知发送失败",riskPolicySaved:"风险政策已保存，并应用于新的模拟买入。",
  errorGeneric:"暂时无法完成请求，请重试。",errorSignIn:"请先登录。",errorService:"模拟组合服务暂时不可用。",errorInvalidOrder:"请输入有效证券、买卖方向和整数数量。",errorSetup:"请先完成模拟组合设置。",errorNoQuote:"该证券目前没有可用行情。",errorMarketQuantity:"数量不符合该市场的交易单位规则。",errorStaleQuote:"行情已经过期，因此禁止模拟成交。",errorReanalysisRequired:"最新价格已离开分析进场区，请先执行完整分析再模拟买入。",errorDrawdown:"组合回撤已达到 {max}% 熔断线，暂停新买入。",errorT1:"卖出数量超过当前可卖 A 股持仓（T+1）。",errorPosition:"该订单会超过“{plan}”计划 {max}% 的单只证券上限。",errorMarket:"该订单会超过 {max}% 的单一市场上限。",errorSector:"该订单会超过 {max}% 的单一行业上限。",errorMarketDisabled:"{market} 尚未启用模拟买入，请先在设置中开启。",errorTradeRisk:"分析停损下的损失为 {riskPct}%，超过 {max}% 上限；最多可买 {maximumQuantity}，估算最低资金为 {minimumCapital}。",errorRiskPolicy:"自定义风险政策无效：{rule}。",errorCash:"计入汇率和交易成本后，模拟现金不足。",errorPortfolio:"模拟组合暂时不可用。",errorOrder:"模拟订单未能完成。",errorCapitalRequired:"模拟资金必须大于零。",errorCapitalReduction:"当前仍有持仓，模拟本金不能低于 {minimum}；请先卖出部分持仓。",errorCurrencyLocked:"已有模拟交易后，基准货币锁定为 {currency}。",errorSettings:"设置未能保存。",
};

const zhTW: Record<CopyKey,string> = {
  ...zhCN,
  language:"語言",mainNavigation:"主導覽",researchDesk:"研究工作台",dataStatus:"資料狀態",dashboard:"總覽",scanner:"市場掃描",signals:"訊號中心",security:"證券研究",
  refreshQuotes:"更新最新行情",refreshingQuotes:"正在更新行情 {processed}/{total}",refreshComplete:"已直接從公開市場來源更新 {updated} 筆行情（{failed} 筆失敗）；模型分數仍沿用最近一次完整分析。",refreshFailed:"伺服器未能更新公開市場行情。",
  fullAnalysis:"執行完整分析",fullAnalysisConfirmTitle:"確認完整分析",fullAnalysisConfirmBody:"雲端模型會重新取得歷史量價，並計算評分、信心與交易計畫。公開資料始終只產生 SHADOW 訊號。",analysisScope:"分析範圍",analysisEstimate:"預計標的",analysisFirstBackfill:"歷史模式",analysisFirstBackfillValue:"若無雲端歷史產物則回填五年；否則採七日重疊增量更新",cancel:"取消",startAnalysis:"開始分析",analysisQueued:"雲端分析已排隊",analysisActive:"完整分析進行中",analysisProgress:"已完成 {completed}/{total} 個市場資產桶",analysisJobCount:"最近 {count} 個分析工作",analysisCloudMissing:"雲端分析尚未設定。請先連接公開 GitHub 倉庫、工作流程 Token 與 Secrets。",analysisStarted:"完整分析已啟動，重新整理頁面或登入後仍可繼續查看進度。",analysisComplete:"完整分析已完成，達標的市場資產桶已啟用。",analysisPartial:"部分分析完成；成功桶已啟用，失敗桶繼續沿用舊結果。",analysisFailed:"完整分析失敗；未啟用任何不完整結果。",analysisStalled:"分析心跳中斷；工作鎖已釋放，可以重新執行。",phaseQueued:"排隊中",phaseDiscovery:"探索證券",phaseHistory:"更新五年歷史",phaseEnrichment:"補充分類資料",phaseScoring:"評分與門檻判斷",phaseUploading:"上傳並啟用",phaseComplete:"完成",analysisTime:"模型分析時間",quoteTime:"最新行情時間",analysisPrice:"分析時價格",reanalysisRequired:"需要完整分析",reanalysisBuyBlocked:"最新價格已離開原進場區。完整分析重新計算交易計畫前，禁止新的模擬買進。",
  modelTrack:"模型版本",activeModel:"目前有效模型",candidateModel:"分市場模型 v2.2",candidateLocked:"v2.2 對每個市場與資產類型使用獨立配置；各桶通過暫定回測與 30 個交易日驗證前均維持 SHADOW。",entryQuality:"進場品質",high52Distance:"距離 52 週高點",high5yDistance:"距離五年高點",extensionAtr:"距離 SMA20",breakoutLevel:"突破位",volumeRatio:"成交量／20 日中位量",closeLocation:"收盤位置",marketRegime:"市場狀態",marketBreadth:"站上 SMA50 比例",plannedR:"計畫 R 倍數",chart5y:"五年價格與進場圖",candidatePaperLocked:"此 v2.2 市場配置尚未達到 ACTIVE_SHADOW，因此禁止模擬買進。",candidateAwaiting:"請執行完整分析，為目前範圍產生 v2.2 分市場結果。",modelProfile:"市場模型配置",strategyFamily:"策略族",gatePreset:"門檻配置",profileStatus:"配置驗證狀態",profileCalibrating:"校準中",profileBacktestPassed:"回測已通過",profileShadowValidating:"30 日影子驗證",profileActiveShadow:"已啟用影子配置",profileRejected:"未通過",
  fullScan:"全市場掃描",discovered:"發現標的",analyzed:"完成分析",failed:"分析失敗",fallback:"備用來源",running:"執行中",universeTarget:"每個市場 500 檔股票 + 100 檔 ETF",
  shadowBuy:"影子買進",watch:"觀察",hardGated:"風險門檻阻擋",ibkrFeed:"IBKR 行情",off:"未啟用",ranked:"檔已排名",limited:"有限樣本",
  stock:"股票",buy:"買進",hold:"持有",reduce:"減碼",exit:"退出",formal:"正式",realtime:"即時",delayed:"延遲",fallbackData:"備用來源",stale:"過期",
  trendConfirmed:"趨勢確認",trendUnconfirmed:"趨勢未確認",momentumLeadership:"動能領先",momentumMixed:"動能混合",riskControlled:"風險受控",volatilityElevated:"波動率偏高",liquidityAcceptable:"流動性合格",liquidityThin:"流動性不足",formalGateActive:"正式門檻已啟用",ibkrNotConnected:"IBKR 尚未連線",
  insufficientHistory:"歷史資料不足",staleData:"資料已過期",sourceWarning:"資料源警告",invalidPrice:"價格無效",
  portfolioEyebrow:"模擬交易／投資組合",loading:"載入中…",setupButton:"前往設定",symbol:"證券代碼",quantity:"數量",sellable:"可賣",averagePrice:"成本／現價",baseValue:"基準幣值",pnl:"損益",sell:"模擬賣出",positions:"持倉",equity:"淨值",cash:"現金",unrealizedPnl:"未實現損益",drawdown:"回撤",feeNotice:"費用、稅與匯率會在伺服器重新計算",
  refreshPositions:"更新持倉行情",refreshingPositions:"正在更新持倉行情…",portfolioQuotesUpdated:"已更新 {updated} 筆持倉行情（{failed} 筆失敗）。",quoteData:"行情來源／時間",errorQuoteRefresh:"未能更新持倉行情。",
  holdingAdvice:"持倉投資建議",holdingAdviceNote:"更新行情只會重算價格觸發條件與組合曝險；評分與交易計畫只在完整分析後更新。",latestQuote:"最新行情",analysisSnapshot:"模型分析快照",costCurrent:"成本／現價",holdingReturn:"持倉報酬率",portfolioWeights:"單檔／市場／產業占比",scoreConfidence:"評分／信心",tradeGuardrails:"停損／目標",suggestedAction:"建議操作",recommendedSell:"建議賣出數量",useSuggestion:"採用建議",noSellable:"目前沒有可賣數量",newBuysPaused:"組合回撤已觸發熔斷，暫停新的模擬買進。",analysisUnavailable:"沒有可用的目前 v2 分析；請先更新行情並執行完整分析。",holdingDisclaimer:"這是依規則產生的模擬持倉建議，不承諾報酬；操作前請核對判斷依據。",
  riskLimits:"風險限制",riskPlan:"風險計畫",singleTradeRisk:"單筆停損風險",maxPosition:"單一證券上限",maxSector:"單一產業上限",maxMarket:"單一市場上限",drawdownBreaker:"回撤熔斷線",capitalFirst:"保本優先",balanced:"均衡成長",growth:"積極成長",minimumLotRule:"首次最小整手可超過單一證券、產業及市場曝險上限，但絕不放寬停損風險、回撤、訊號、行情與現金門檻。",minimumLotException:"最小交易整手例外",investmentMarkets:"允許投資的市場",investmentMarketsNote:"七個市場仍完整顯示研究結果；只有選取的市場允許模擬買進。",customRiskPolicy:"自訂風險政策",resetRiskTemplate:"恢復計畫模板",allowMinimumLot:"允許可稽核的首次整手例外",marketLimit:"{market} 市場上限",effectiveLimit:"實際生效上限",riskPolicyPreview:"生效預覽：單一證券 {position}%，單一產業 {sector}%；已選市場上限合計 {marketTotal}%，合計低於 100% 時至少刻意保留 {cash}% 現金。",riskPolicyConflictPreview:"限制互相矛盾：單一證券上限必須在允許範圍內，且不得高於產業上限或任何已選市場上限。",
  marketRules:"市場規則",settlement:"交割",tradingUnit:"交易單位",variable:"依證券而定",sessionOpen:"預估開市",sessionClosed:"預估休市",ruleVersion:"規則版本",
  orderHistory:"訂單紀錄",orderTime:"時間",side:"方向",filledPrice:"成交價",feesTaxes:"費用與稅",realizedPnl:"已實現損益",status:"狀態",filled:"已成交",noRecords:"暫無紀錄",sellCompleted:"模擬賣出完成",
  backtestEyebrow:"模型／驗證",formalLocked:"正式訊號尚未解鎖",validationRequired:"必須通過回測及 30 個交易日影子驗證。",minimumTrades:"最低交易筆數",profitFactor:"獲利因子",sharpe:"夏普比率",shadowDays:"影子驗證天數",pending:"待驗證",passed:"已通過",locked:"未解鎖",
  notStarted:"尚未開始",inProgress:"進行中",migrationPending:"移轉待完成",complete:"完成",partial:"部分完成",
  healthEyebrow:"系統／資料健康",primaryFeed:"正式即時主行情",shadowUntilValidated:"完成 IBKR 行情訂閱及驗證前，公開來源候選仍只顯示影子訊號。",noSnapshot:"暫無快照",healthy:"正常",degraded:"降級",unavailable:"不可用",operational:"運作正常",waiting:"等待資料",daily:"日線",unknown:"未知",
  settingsEyebrow:"僅限擁有者／設定",baseCurrency:"基準貨幣",paperCapital:"模擬資金",email:"電子郵件",enableEmail:"透過 Resend 啟用 Email 提醒",saved:"已儲存",saveFailed:"儲存失敗",capitalSynced:"已儲存：模擬本金 {capital}；現金同步調整 {delta}。",inAppEmailDelivered:"站內與 Email 通知均已送達",inAppDelivered:"站內通知已送達；Email 尚未設定",alertFailed:"通知傳送失敗",
  errorGeneric:"暫時無法完成要求，請重試。",errorSignIn:"請先登入。",errorService:"模擬組合服務暫時不可用。",errorInvalidOrder:"請輸入有效證券、買賣方向與整數數量。",errorSetup:"請先完成模擬組合設定。",errorNoQuote:"此證券目前沒有可用行情。",errorMarketQuantity:"數量不符合此市場的交易單位規則。",errorStaleQuote:"行情已經過期，因此禁止模擬成交。",errorReanalysisRequired:"最新價格已離開分析進場區，請先執行完整分析再模擬買進。",errorDrawdown:"組合回撤已達 {max}% 熔斷線，暫停新買進。",errorT1:"賣出數量超過目前可賣 A 股持倉（T+1）。",errorPosition:"此訂單會超過「{plan}」計畫 {max}% 的單一證券上限。",errorMarket:"此訂單會超過 {max}% 的單一市場上限。",errorSector:"此訂單會超過 {max}% 的單一產業上限。",errorMarketDisabled:"{market} 尚未允許模擬買進，請先在設定中啟用。",errorTradeRisk:"分析停損下的損失為 {riskPct}%，超過 {max}% 上限；最多可買 {maximumQuantity}，估算最低資金為 {minimumCapital}。",errorRiskPolicy:"自訂風險政策無效：{rule}。",errorCash:"計入匯率與交易成本後，模擬現金不足。",errorPortfolio:"模擬組合暫時不可用。",errorOrder:"模擬訂單未能完成。",errorCapitalRequired:"模擬資金必須大於零。",errorCapitalReduction:"目前仍有持倉，模擬本金不得低於 {minimum}；請先賣出部分持倉。",errorCurrencyLocked:"已有模擬交易後，基準貨幣鎖定為 {currency}。",errorSettings:"設定未能儲存。",
};

const ja: Record<CopyKey,string> = {
  ...en,
  language:"言語",mainNavigation:"メインナビゲーション",researchDesk:"リサーチデスク",model:"モデル",holdingPeriod:"2～12週間のスイング",dataStatus:"データ状態",dashboard:"概要",scanner:"市場スキャン",signals:"シグナル",security:"銘柄リサーチ",
  refreshQuotes:"最新価格を更新",refreshingQuotes:"価格を更新中 {processed}/{total}",refreshComplete:"公開市場ソースから {updated} 件を更新しました（{failed} 件失敗）。モデルスコアは直近の完全分析を維持します。",refreshFailed:"サーバーで公開市場価格を更新できませんでした。",
  fullAnalysis:"完全分析を実行",fullAnalysisConfirmTitle:"完全分析の確認",fullAnalysisConfirmBody:"クラウドモデルが過去の価格・出来高を更新し、スコア、信頼度、取引計画を再計算します。公開データは常に SHADOW のままです。",analysisScope:"分析範囲",analysisEstimate:"推定銘柄数",analysisFirstBackfill:"履歴モード",analysisFirstBackfillValue:"クラウド履歴がなければ5年分を取得し、それ以外は7日重複で差分更新",cancel:"キャンセル",startAnalysis:"分析開始",analysisQueued:"クラウド分析を待機中",analysisActive:"完全分析を実行中",analysisProgress:"{completed}/{total} バケット完了",analysisJobCount:"直近 {count} 件の分析ジョブ",analysisCloudMissing:"クラウド分析が未設定です。公開 GitHub リポジトリ、ワークフロー Token、Secrets を接続してください。",analysisStarted:"完全分析を開始しました。更新や再ログイン後も進捗を確認できます。",analysisComplete:"完全分析が完了し、基準を満たすバケットを有効化しました。",analysisPartial:"一部完了しました。成功バケットは有効化し、失敗バケットは以前の結果を維持します。",analysisFailed:"完全分析に失敗し、不完全な結果は有効化されませんでした。",analysisStalled:"分析のハートビートが停止しました。ロックを解放したため再実行できます。",phaseQueued:"待機中",phaseDiscovery:"銘柄を探索中",phaseHistory:"5年履歴を更新中",phaseEnrichment:"分類情報を補完中",phaseScoring:"採点と条件判定中",phaseUploading:"アップロードと有効化中",phaseComplete:"完了",analysisTime:"モデル分析時刻",quoteTime:"最新価格時刻",analysisPrice:"分析時価格",reanalysisRequired:"完全分析が必要",reanalysisBuyBlocked:"最新価格が元のエントリー範囲外です。完全分析で取引計画を再計算するまで、新規の模擬買いはできません。",
  modelTrack:"モデル系列",activeModel:"現在の有効モデル",candidateModel:"市場別モデル v2.2",candidateLocked:"v2.2 は市場・資産種別ごとに独立した設定を使います。暫定バックテストと30取引日の検証を通過するまで各バケットは SHADOW のままです。",entryQuality:"エントリー品質",high52Distance:"52週高値からの距離",high5yDistance:"5年高値からの距離",extensionAtr:"SMA20からの距離",breakoutLevel:"ブレイク水準",volumeRatio:"出来高／20日中央値",closeLocation:"終値位置",marketRegime:"市場状態",marketBreadth:"SMA50超の比率",plannedR:"計画R倍率",chart5y:"5年価格・エントリー図",candidatePaperLocked:"この v2.2 市場設定はまだ ACTIVE_SHADOW ではないため、模擬買いできません。",candidateAwaiting:"完全分析を実行し、この範囲の v2.2 市場別結果を作成してください。",modelProfile:"市場モデル設定",strategyFamily:"戦略ファミリー",gatePreset:"判定プリセット",profileStatus:"設定の検証状態",profileCalibrating:"校正中",profileBacktestPassed:"バックテスト合格",profileShadowValidating:"30日シャドー検証",profileActiveShadow:"有効なシャドー設定",profileRejected:"不合格",
  fullScan:"全市場スキャン",discovered:"検出",analyzed:"分析済み",failed:"失敗",fallback:"代替ソース",running:"実行中",universeTarget:"市場ごとに株式500銘柄＋ETF100銘柄",shadowBuy:"シャドー買い",watch:"監視",hardGated:"リスク制限",ibkrFeed:"IBKRデータ",off:"未設定",ranked:"件を順位付け",limited:"限定データ",
  stock:"株式",buy:"買い",hold:"保有",reduce:"縮小",exit:"手仕舞い",shadow:"シャドー",formal:"正式",realtime:"リアルタイム",delayed:"遅延",fallbackData:"代替",stale:"期限切れ",
  trendConfirmed:"トレンド確認",trendUnconfirmed:"トレンド未確認",momentumLeadership:"モメンタム優位",momentumMixed:"モメンタム混在",riskControlled:"リスク管理良好",volatilityElevated:"ボラティリティ上昇",liquidityAcceptable:"流動性良好",liquidityThin:"流動性不足",formalGateActive:"正式ゲート有効",ibkrNotConnected:"IBKR未接続",insufficientHistory:"履歴不足",staleData:"データ期限切れ",sourceWarning:"データソース警告",invalidPrice:"価格無効",
  portfolioEyebrow:"模擬取引／ポートフォリオ",loading:"読み込み中…",setupButton:"設定へ",symbol:"銘柄コード",market:"市場",quantity:"数量",sellable:"売却可能",averagePrice:"平均単価／現在値",baseValue:"基準通貨価値",pnl:"損益",sell:"模擬売却",positions:"保有銘柄",equity:"純資産",cash:"現金",unrealizedPnl:"含み損益",drawdown:"ドローダウン",feeNotice:"手数料・税・為替はサーバーで再計算されます",
  refreshPositions:"保有銘柄の価格を更新",refreshingPositions:"保有銘柄の価格を更新中…",portfolioQuotesUpdated:"保有銘柄の価格を {updated} 件更新しました（{failed} 件失敗）。",quoteData:"価格情報源／時刻",errorQuoteRefresh:"保有銘柄の価格を更新できませんでした。",
  holdingAdvice:"保有銘柄の投資判断",holdingAdviceNote:"価格更新では価格条件とポートフォリオ比率のみ再判定します。スコアと取引計画は完全分析後にだけ更新されます。",latestQuote:"最新価格",analysisSnapshot:"モデル分析時点",costCurrent:"取得単価／現在値",holdingReturn:"保有リターン",portfolioWeights:"銘柄／市場／業種比率",scoreConfidence:"スコア／信頼度",tradeGuardrails:"損切り／目標",suggestedAction:"推奨対応",recommendedSell:"推奨売却数量",useSuggestion:"推奨値を使用",noSellable:"現在売却可能な数量はありません",newBuysPaused:"ポートフォリオのドローダウン停止線により新規模擬買いを停止しています。",analysisUnavailable:"有効な v2 分析がありません。価格更新後に完全分析を実行してください。",holdingDisclaimer:"ルールに基づく模擬判断であり、収益を保証しません。実行前に根拠を確認してください。",
  riskLimits:"リスク制限",riskPlan:"リスクプラン",singleTradeRisk:"1取引の損切りリスク",maxPosition:"1銘柄上限",maxSector:"セクター上限",maxMarket:"市場上限",drawdownBreaker:"ドローダウン停止線",capitalFirst:"元本保全",balanced:"バランス成長",growth:"積極成長",minimumLotRule:"最初の最低売買単位だけは銘柄・セクター・市場比率の上限を超過できますが、損切りリスク、ドローダウン、シグナル、価格鮮度、現金の条件は緩和しません。",minimumLotException:"最低売買単位の例外",investmentMarkets:"投資を許可する市場",investmentMarketsNote:"7市場のリサーチ結果はすべて表示し、模擬買いは選択した市場だけで許可します。",customRiskPolicy:"カスタムリスク方針",resetRiskTemplate:"プラン初期値に戻す",allowMinimumLot:"監査可能な初回最低単位の例外を許可",marketLimit:"{market} 市場上限",effectiveLimit:"有効な上限",riskPolicyPreview:"有効値の確認：1銘柄 {position}%、セクター {sector}%、選択市場の上限合計 {marketTotal}%です。合計が100%未満なら最低 {cash}% を現金として意図的に残します。",riskPolicyConflictPreview:"制限が矛盾しています。1銘柄上限は許容範囲内で、セクター上限および選択した各市場上限以下にしてください。",
  marketRules:"市場ルール",settlement:"決済",tradingUnit:"取引単位",variable:"銘柄別",sessionOpen:"推定取引中",sessionClosed:"推定休場",ruleVersion:"ルール版",orderHistory:"注文履歴",orderTime:"時刻",side:"売買",filledPrice:"約定価格",feesTaxes:"手数料・税",realizedPnl:"実現損益",status:"状態",filled:"約定済み",noRecords:"記録なし",sellCompleted:"模擬売却完了",
  backtestEyebrow:"モデル／検証",formalLocked:"正式シグナルは未解除",validationRequired:"バックテストと30取引日のシャドー検証が必要です。",minimumTrades:"最低取引数",profitFactor:"プロフィットファクター",sharpe:"シャープレシオ",shadowDays:"シャドー日数",pending:"検証待ち",passed:"合格",locked:"未解除",
  notStarted:"未開始",inProgress:"進行中",migrationPending:"移行待ち",complete:"完了",partial:"一部完了",
  healthEyebrow:"システム／データ状態",primaryFeed:"正式リアルタイム主データ",shadowUntilValidated:"IBKR購読と検証完了までは、公開情報の候補をシャドーシグナルとして表示します。",noSnapshot:"スナップショットなし",healthy:"正常",degraded:"低下",unavailable:"利用不可",operational:"稼働中",waiting:"データ待ち",daily:"日次",unknown:"不明",
  settingsEyebrow:"所有者専用／設定",baseCurrency:"基準通貨",paperCapital:"模擬資金",email:"メール",enableEmail:"Resendでメール通知を有効化",saved:"保存しました",saveFailed:"保存失敗",capitalSynced:"保存しました：模擬元本 {capital}、現金調整 {delta}。",inAppEmailDelivered:"アプリ内・メール通知を送信しました",inAppDelivered:"アプリ内通知を送信。メール未設定",alertFailed:"通知失敗",
  errorGeneric:"処理を完了できませんでした。再試行してください。",errorSignIn:"ログインが必要です。",errorService:"模擬ポートフォリオは一時的に利用できません。",errorInvalidOrder:"有効な銘柄、売買、整数数量を入力してください。",errorSetup:"先に模擬ポートフォリオを設定してください。",errorNoQuote:"この銘柄の現在値を取得できません。",errorMarketQuantity:"数量がこの市場の取引単位に適合しません。",errorStaleQuote:"価格が古いため模擬約定できません。",errorReanalysisRequired:"最新価格が分析時のエントリー範囲外です。完全分析後に模擬買いを実行してください。",errorDrawdown:"ドローダウンが{max}%の停止線に達し、新規買いを停止しました。",errorT1:"売却数量が現在売却可能なA株数量を超えています（T+1）。",errorPosition:"この注文は「{plan}」プランの1銘柄上限{max}%を超えます。",errorMarket:"この注文は市場上限{max}%を超えます。",errorSector:"この注文はセクター上限{max}%を超えます。",errorMarketDisabled:"{market} は模擬買い対象外です。設定で有効にしてください。",errorTradeRisk:"分析済み損切りでの損失 {riskPct}% は上限 {max}% を超えます。最大数量: {maximumQuantity}、推定最低資金: {minimumCapital}。",errorRiskPolicy:"カスタムリスク方針が無効です: {rule}。",errorCash:"為替と取引費用を含めると模擬現金が不足します。",errorPortfolio:"模擬ポートフォリオを取得できません。",errorOrder:"模擬注文を完了できませんでした。",errorCapitalRequired:"模擬資金は0より大きい必要があります。",errorCapitalReduction:"保有中のため、模擬元本を {minimum} 未満にできません。先に売却してください。",errorCurrencyLocked:"模擬取引後の基準通貨は {currency} に固定されています。",errorSettings:"設定を保存できませんでした。",
};

const ko: Record<CopyKey,string> = {
  ...en,
  language:"언어",mainNavigation:"주 탐색",researchDesk:"리서치 데스크",model:"모델",holdingPeriod:"2~12주 스윙",dataStatus:"데이터 상태",dashboard:"개요",scanner:"시장 스캔",signals:"신호",security:"종목 리서치",
  refreshQuotes:"최신 시세 업데이트",refreshingQuotes:"시세 업데이트 중 {processed}/{total}",refreshComplete:"공개 시장 소스에서 시세 {updated}건을 업데이트했습니다({failed}건 실패). 모델 점수는 최근 전체 분석을 유지합니다.",refreshFailed:"서버가 공개 시장 시세를 업데이트하지 못했습니다.",
  fullAnalysis:"전체 분석 실행",fullAnalysisConfirmTitle:"전체 분석 확인",fullAnalysisConfirmBody:"클라우드 모델이 과거 가격·거래량을 갱신하고 점수, 신뢰도, 거래 계획을 다시 계산합니다. 공개 데이터는 항상 SHADOW로 유지됩니다.",analysisScope:"분석 범위",analysisEstimate:"예상 종목 수",analysisFirstBackfill:"이력 모드",analysisFirstBackfillValue:"클라우드 이력이 없으면 5년을 채우고, 있으면 7일 중첩 증분 업데이트",cancel:"취소",startAnalysis:"분석 시작",analysisQueued:"클라우드 분석 대기 중",analysisActive:"전체 분석 진행 중",analysisProgress:"{completed}/{total}개 버킷 완료",analysisJobCount:"최근 분석 작업 {count}개",analysisCloudMissing:"클라우드 분석이 설정되지 않았습니다. 공개 GitHub 저장소, 워크플로 Token과 Secrets를 연결하세요.",analysisStarted:"전체 분석을 시작했습니다. 새로고침하거나 다시 로그인해도 진행 상태를 볼 수 있습니다.",analysisComplete:"전체 분석을 완료하고 기준을 통과한 버킷을 활성화했습니다.",analysisPartial:"일부 분석을 완료했습니다. 성공 버킷은 활성화하고 실패 버킷은 이전 결과를 유지합니다.",analysisFailed:"전체 분석에 실패했으며 불완전한 결과는 활성화하지 않았습니다.",analysisStalled:"분석 하트비트가 중단되었습니다. 작업 잠금을 해제했으므로 다시 실행할 수 있습니다.",phaseQueued:"대기 중",phaseDiscovery:"종목 탐색 중",phaseHistory:"5년 이력 업데이트 중",phaseEnrichment:"분류 정보 보강 중",phaseScoring:"점수 및 조건 판정 중",phaseUploading:"업로드 및 활성화 중",phaseComplete:"완료",analysisTime:"모델 분석 시간",quoteTime:"최신 시세 시간",analysisPrice:"분석 당시 가격",reanalysisRequired:"전체 분석 필요",reanalysisBuyBlocked:"최신 가격이 기존 진입 구간을 벗어났습니다. 전체 분석으로 거래 계획을 다시 계산할 때까지 새 모의 매수를 차단합니다.",
  modelTrack:"모델 계열",activeModel:"현재 활성 모델",candidateModel:"시장별 모델 v2.2",candidateLocked:"v2.2는 시장과 자산 유형마다 별도 구성을 사용합니다. 잠정 백테스트와 30거래일 검증을 통과할 때까지 각 버킷은 SHADOW로 유지됩니다.",entryQuality:"진입 품질",high52Distance:"52주 고점 대비",high5yDistance:"5년 고점 대비",extensionAtr:"SMA20 거리",breakoutLevel:"돌파선",volumeRatio:"거래량／20일 중앙값",closeLocation:"종가 위치",marketRegime:"시장 상태",marketBreadth:"SMA50 상회 비율",plannedR:"계획 R 배수",chart5y:"5년 가격·진입 차트",candidatePaperLocked:"이 v2.2 시장 구성은 아직 ACTIVE_SHADOW가 아니므로 모의 매수를 차단합니다.",candidateAwaiting:"전체 분석을 실행하여 이 범위의 v2.2 시장별 결과를 생성하세요.",modelProfile:"시장 모델 구성",strategyFamily:"전략 계열",gatePreset:"기준 프리셋",profileStatus:"구성 검증 상태",profileCalibrating:"보정 중",profileBacktestPassed:"백테스트 통과",profileShadowValidating:"30일 섀도 검증",profileActiveShadow:"활성 섀도 구성",profileRejected:"통과 실패",
  fullScan:"전체 시장 스캔",discovered:"발견",analyzed:"분석 완료",failed:"실패",fallback:"대체 소스",running:"실행 중",universeTarget:"시장별 주식 500개 + ETF 100개",shadowBuy:"섀도 매수",watch:"관찰",hardGated:"위험 제한",ibkrFeed:"IBKR 시세",off:"비활성",ranked:"개 순위",limited:"제한 데이터",
  stock:"주식",buy:"매수",hold:"보유",reduce:"축소",exit:"청산",shadow:"섀도",formal:"정식",realtime:"실시간",delayed:"지연",fallbackData:"대체",stale:"만료",
  trendConfirmed:"추세 확인",trendUnconfirmed:"추세 미확인",momentumLeadership:"모멘텀 우위",momentumMixed:"모멘텀 혼조",riskControlled:"위험 통제",volatilityElevated:"변동성 상승",liquidityAcceptable:"유동성 양호",liquidityThin:"유동성 부족",formalGateActive:"정식 기준 활성",ibkrNotConnected:"IBKR 미연결",insufficientHistory:"이력 부족",staleData:"데이터 만료",sourceWarning:"데이터 소스 경고",invalidPrice:"가격 오류",
  portfolioEyebrow:"모의 거래／포트폴리오",loading:"불러오는 중…",setupButton:"설정하기",symbol:"종목 코드",market:"시장",quantity:"수량",sellable:"매도 가능",averagePrice:"평균가／현재가",baseValue:"기준 통화 가치",pnl:"손익",sell:"모의 매도",positions:"보유 종목",equity:"순자산",cash:"현금",unrealizedPnl:"미실현 손익",drawdown:"낙폭",feeNotice:"수수료, 세금 및 환율은 서버에서 재계산됩니다",
  refreshPositions:"보유 종목 시세 업데이트",refreshingPositions:"보유 종목 시세 업데이트 중…",portfolioQuotesUpdated:"보유 종목 시세 {updated}건을 업데이트했습니다({failed}건 실패).",quoteData:"시세 출처／시간",errorQuoteRefresh:"보유 종목 시세를 업데이트하지 못했습니다.",
  holdingAdvice:"보유 종목 투자 판단",holdingAdviceNote:"시세 업데이트는 가격 조건과 포트폴리오 비중만 다시 계산합니다. 점수와 거래 계획은 전체 분석 후에만 변경됩니다.",latestQuote:"최신 시세",analysisSnapshot:"모델 분석 시점",costCurrent:"평균가／현재가",holdingReturn:"보유 수익률",portfolioWeights:"종목／시장／업종 비중",scoreConfidence:"점수／신뢰도",tradeGuardrails:"손절／목표",suggestedAction:"권장 조치",recommendedSell:"권장 매도 수량",useSuggestion:"권장값 사용",noSellable:"현재 매도 가능한 수량이 없습니다",newBuysPaused:"포트폴리오 낙폭 중단선으로 신규 모의 매수를 중지했습니다.",analysisUnavailable:"유효한 v2 분석이 없습니다. 시세 업데이트 후 전체 분석을 실행하세요.",holdingDisclaimer:"규칙 기반 모의 판단이며 수익을 보장하지 않습니다. 실행 전에 근거를 확인하세요.",
  riskLimits:"위험 제한",riskPlan:"위험 계획",singleTradeRisk:"거래당 손절 위험",maxPosition:"종목당 한도",maxSector:"업종 한도",maxMarket:"시장 한도",drawdownBreaker:"낙폭 중단선",capitalFirst:"원금 보전",balanced:"균형 성장",growth:"적극 성장",minimumLotRule:"첫 최소 거래 단위만 종목·업종·시장 비중 한도를 초과할 수 있지만 손절 위험, 낙폭, 신호, 시세 신선도 및 현금 기준은 완화하지 않습니다.",minimumLotException:"최소 거래 단위 예외",investmentMarkets:"투자 허용 시장",investmentMarketsNote:"7개 시장의 연구 결과는 모두 표시하며 모의 매수는 선택한 시장에서만 허용합니다.",customRiskPolicy:"사용자 위험 정책",resetRiskTemplate:"계획 템플릿으로 초기화",allowMinimumLot:"감사 가능한 첫 최소 단위 예외 허용",marketLimit:"{market} 시장 한도",effectiveLimit:"실제 적용 한도",riskPolicyPreview:"적용 미리보기: 종목당 {position}%, 업종당 {sector}%, 선택 시장 한도 합계 {marketTotal}%입니다. 합계가 100% 미만이면 최소 {cash}%를 의도적으로 현금으로 남깁니다.",riskPolicyConflictPreview:"제한이 서로 충돌합니다. 종목 한도는 허용 범위 안에 있어야 하며 업종 또는 선택한 각 시장 한도를 초과할 수 없습니다.",
  marketRules:"시장 규칙",settlement:"결제",tradingUnit:"거래 단위",variable:"종목별",sessionOpen:"예상 개장",sessionClosed:"예상 휴장",ruleVersion:"규칙 버전",orderHistory:"주문 기록",orderTime:"시간",side:"구분",filledPrice:"체결가",feesTaxes:"수수료·세금",realizedPnl:"실현 손익",status:"상태",filled:"체결",noRecords:"기록 없음",sellCompleted:"모의 매도 완료",
  backtestEyebrow:"모델／검증",formalLocked:"정식 신호 잠김",validationRequired:"백테스트 및 30거래일 섀도 검증이 필요합니다.",minimumTrades:"최소 거래 수",profitFactor:"수익 팩터",sharpe:"샤프 지수",shadowDays:"섀도 일수",pending:"검증 대기",passed:"통과",locked:"잠김",
  notStarted:"시작 전",inProgress:"진행 중",migrationPending:"마이그레이션 대기",complete:"완료",partial:"일부 완료",
  healthEyebrow:"시스템／데이터 상태",primaryFeed:"정식 실시간 주 시세",shadowUntilValidated:"IBKR 구독 및 검증 전에는 공개 소스 후보를 섀도 신호로 표시합니다.",noSnapshot:"스냅샷 없음",healthy:"정상",degraded:"저하",unavailable:"사용 불가",operational:"정상 운영",waiting:"데이터 대기",daily:"일간",unknown:"알 수 없음",
  settingsEyebrow:"소유자 전용／설정",baseCurrency:"기준 통화",paperCapital:"모의 자금",email:"이메일",enableEmail:"Resend 이메일 알림 활성화",saved:"저장됨",saveFailed:"저장 실패",capitalSynced:"저장됨: 모의 원금 {capital}, 현금 조정 {delta}.",inAppEmailDelivered:"앱 및 이메일 알림 전송 완료",inAppDelivered:"앱 알림 전송 완료; 이메일 미설정",alertFailed:"알림 실패",
  errorGeneric:"요청을 완료하지 못했습니다. 다시 시도하세요.",errorSignIn:"로그인이 필요합니다.",errorService:"모의 포트폴리오 서비스를 일시적으로 사용할 수 없습니다.",errorInvalidOrder:"유효한 종목, 매매 구분 및 정수 수량을 입력하세요.",errorSetup:"먼저 모의 포트폴리오를 설정하세요.",errorNoQuote:"현재 시세를 사용할 수 없습니다.",errorMarketQuantity:"수량이 해당 시장의 거래 단위 규칙에 맞지 않습니다.",errorStaleQuote:"시세가 오래되어 모의 체결이 차단되었습니다.",errorReanalysisRequired:"최신 가격이 분석 진입 구간을 벗어났습니다. 전체 분석 후 모의 매수를 실행하세요.",errorDrawdown:"포트폴리오 낙폭이 {max}% 중단선에 도달해 신규 매수를 중지했습니다.",errorT1:"매도 수량이 현재 매도 가능한 A주 수량을 초과합니다(T+1).",errorPosition:"이 주문은 '{plan}' 계획의 종목당 {max}% 한도를 초과합니다.",errorMarket:"이 주문은 시장 한도 {max}%를 초과합니다.",errorSector:"이 주문은 업종 한도 {max}%를 초과합니다.",errorCash:"환율과 거래 비용을 반영하면 모의 현금이 부족합니다.",errorPortfolio:"모의 포트폴리오를 불러올 수 없습니다.",errorOrder:"모의 주문을 완료하지 못했습니다.",errorCapitalRequired:"모의 자금은 0보다 커야 합니다.",errorCapitalReduction:"보유 종목이 있어 모의 원금을 {minimum} 미만으로 줄일 수 없습니다. 먼저 매도하세요.",errorCurrencyLocked:"모의 거래 후 기준 통화는 {currency}로 잠깁니다.",errorSettings:"설정을 저장하지 못했습니다.",
};

Object.assign(en,{activeModel:"Current active model"});
Object.assign(zhCN,{activeModel:"当前有效模型"});
Object.assign(ko,{
  errorMarketDisabled:"{market} 시장은 모의 매수 대상이 아닙니다. 설정에서 활성화하세요.",
  errorTradeRisk:"분석 손절 기준 손실 {riskPct}%가 한도 {max}%를 초과합니다. 최대 수량: {maximumQuantity}, 예상 최소 자금: {minimumCapital}.",
  errorRiskPolicy:"사용자 위험 정책이 올바르지 않습니다: {rule}.",
});

const copies: Record<Locale,Record<CopyKey,string>> = { en, "zh-CN":zhCN, "zh-TW":zhTW, ja, ko };

export function tx(locale:Locale, key:CopyKey, params:Params = {}) {
  return Object.entries(params).reduce((text,[name,value]) => text.replaceAll(`{${name}}`, String(value ?? "")), copies[locale]?.[key] ?? en[key]);
}

const codeKeys:Record<string,CopyKey> = {
  STOCK:"stock", ETF:"etf", BUY:"buy", WATCH:"watch", HOLD:"hold", REDUCE:"reduce", EXIT:"exit", SHADOW:"shadow", FORMAL:"formal",
  realtime:"realtime", delayed:"delayed", fallback:"fallbackData", stale:"stale",
  TREND_CONFIRMED:"trendConfirmed", TREND_UNCONFIRMED:"trendUnconfirmed", MOMENTUM_LEADERSHIP:"momentumLeadership", MOMENTUM_MIXED:"momentumMixed", RISK_CONTROLLED:"riskControlled", VOLATILITY_ELEVATED:"volatilityElevated", LIQUIDITY_ACCEPTABLE:"liquidityAcceptable", LIQUIDITY_THIN:"liquidityThin", FORMAL_GATE_ACTIVE:"formalGateActive", IBKR_NOT_CONNECTED:"ibkrNotConnected",
  INSUFFICIENT_HISTORY:"insufficientHistory", STALE_DATA:"staleData", SOURCE_WARNING:"sourceWarning", INVALID_PRICE:"invalidPrice",
  FILLED:"filled", MINIMUM_TRADABLE_LOT:"minimumLotException", OPEN_ESTIMATE:"sessionOpen", CLOSED_ESTIMATE:"sessionClosed", COMPLETED:"passed", PENDING:"pending", PASSED:"passed", LOCKED:"locked", NOT_STARTED:"notStarted", IN_PROGRESS:"inProgress", MIGRATION_PENDING:"migrationPending", COMPLETE:"complete", PARTIAL:"partial", operational:"operational", waiting:"waiting", healthy:"healthy", degraded:"degraded", unavailable:"unavailable", daily:"daily", unknown:"unknown", "public fallback":"fallbackData",
  CALIBRATING:"profileCalibrating", BACKTEST_PASSED:"profileBacktestPassed", SHADOW_VALIDATING:"profileShadowValidating", ACTIVE_SHADOW:"profileActiveShadow", REJECTED:"profileRejected",
};

export function codeText(locale:Locale, code:unknown) {
  const raw = String(code ?? "");
  const v2 = v2Codes[locale]?.[raw];
  if (v2) return v2;
  const key = codeKeys[raw] ?? codeKeys[raw.toUpperCase()];
  return key ? tx(locale,key) : raw.replaceAll("_"," ");
}

const v2Codes:Record<Locale,Record<string,string>> = {
  en:{ WATCH:"Watch",PUBLIC_DATA_SHADOW:"Public-data shadow",NON_GENUINE_OHLCV:"Genuine OHLCV unavailable",SECTOR_UNKNOWN:"Industry unknown",SOURCE_CONFLICT:"Source conflict over 1%",CORPORATE_ACTION_ANOMALY:"Corporate-action anomaly",ETF_STRUCTURE_EXCLUDED:"ETF structure excluded",PRICE_NOT_ABOVE_MA_SET:"Price is not above 20/50/200-day averages",LONG_TREND_NOT_RISING:"50/200-day trend is not rising",MOMENTUM_NOT_POSITIVE:"3/6-month return is not positive",RELATIVE_STRENGTH_BELOW_70:"Relative strength below 70",VOLUME_CONFIRMATION_PENDING:"Volume confirmation pending",RISK_OFF:"Market regime is risk-off",ETF_STRUCTURE_INCOMPLETE:"ETF structure data incomplete",DAILY_SELECTION_CAP:"Daily 3+1 selection cap",SITE_FALLBACK_WATCH_ONLY:"Site fallback is watch-only",PROVISIONAL_BACKTEST:"Provisional backtest",PROVISIONAL_PASSED:"Provisionally passed",PROVISIONAL_FAILED_GATE:"Provisional gate failed",BREAKOUT_READY:"High-quality breakout; entry ready",PULLBACK_READY:"Healthy pullback confirmed; entry ready",WAIT_PULLBACK:"Trend is healthy; wait for a pullback",OVEREXTENDED:"Trend is healthy but overextended; wait at least three sessions",NO_SETUP:"No confirmed entry setup",BLOCKED_REGIME:"Market regime does not permit a new BUY",BLOCKED_DATA:"Benchmark or breadth data is missing",MARKET_CONTEXT_MISSING:"Market benchmark or breadth unavailable",MARKET_RISK_OFF:"Risk-off blocks new BUYs",PRICE_OVEREXTENDED:"Price extension or shock cooling blocks BUY",WAITING_FOR_PULLBACK:"Waiting for a healthy pullback",NO_ENTRY_SETUP:"No breakout or pullback confirmation",STOP_DISTANCE_OUT_OF_RANGE:"Stop distance must be 1.25%–8%",RISK_ON:"Risk-on",NEUTRAL:"Neutral"},
  "zh-CN":{ WATCH:"观察",PUBLIC_DATA_SHADOW:"公开数据影子信号",NON_GENUINE_OHLCV:"缺少真实量价",SECTOR_UNKNOWN:"行业未知",SOURCE_CONFLICT:"来源差异超过 1%",CORPORATE_ACTION_ANOMALY:"公司行动异常",ETF_STRUCTURE_EXCLUDED:"ETF 产品结构不合格",PRICE_NOT_ABOVE_MA_SET:"价格未站上 20/50/200 日均线",LONG_TREND_NOT_RISING:"50/200 日趋势未向上",MOMENTUM_NOT_POSITIVE:"3/6 月收益未同时为正",RELATIVE_STRENGTH_BELOW_70:"相对强度低于 70",VOLUME_CONFIRMATION_PENDING:"等待成交量确认",RISK_OFF:"市场处于避险状态",ETF_STRUCTURE_INCOMPLETE:"ETF 产品结构资料不完整",DAILY_SELECTION_CAP:"达到每日 3+1 选择上限",SITE_FALLBACK_WATCH_ONLY:"网站备用扫描只允许观察",PROVISIONAL_BACKTEST:"暂定回测",PROVISIONAL_PASSED:"暂定通过",PROVISIONAL_FAILED_GATE:"未通过暂定门槛",BREAKOUT_READY:"高质量放量突破，可以进场",PULLBACK_READY:"健康回踩确认，可以进场",WAIT_PULLBACK:"趋势良好，等待健康回踩",OVEREXTENDED:"趋势良好但过度延伸，至少等待三个交易日",NO_SETUP:"尚无确认的进场形态",BLOCKED_REGIME:"市场状态不允许新买入",BLOCKED_DATA:"缺少市场基准或广度资料",MARKET_CONTEXT_MISSING:"市场基准或广度不可用",MARKET_RISK_OFF:"避险状态阻止新买入",PRICE_OVEREXTENDED:"价格延伸或异常波动冷却期阻止买入",WAITING_FOR_PULLBACK:"等待健康回踩",NO_ENTRY_SETUP:"没有突破或回踩确认",STOP_DISTANCE_OUT_OF_RANGE:"止损距离必须在 1.25%–8%",RISK_ON:"积极",NEUTRAL:"中性"},
  "zh-TW":{ WATCH:"觀察",PUBLIC_DATA_SHADOW:"公開資料影子訊號",NON_GENUINE_OHLCV:"缺少真實量價",SECTOR_UNKNOWN:"產業未知",SOURCE_CONFLICT:"來源差異超過 1%",CORPORATE_ACTION_ANOMALY:"公司行動異常",ETF_STRUCTURE_EXCLUDED:"ETF 產品結構不合格",PRICE_NOT_ABOVE_MA_SET:"價格未站上 20/50/200 日均線",LONG_TREND_NOT_RISING:"50/200 日趨勢未向上",MOMENTUM_NOT_POSITIVE:"3/6 月報酬未同時為正",RELATIVE_STRENGTH_BELOW_70:"相對強度低於 70",VOLUME_CONFIRMATION_PENDING:"等待成交量確認",RISK_OFF:"市場處於避險狀態",ETF_STRUCTURE_INCOMPLETE:"ETF 產品結構資料不完整",DAILY_SELECTION_CAP:"達到每日 3+1 選擇上限",SITE_FALLBACK_WATCH_ONLY:"網站備用掃描只允許觀察",PROVISIONAL_BACKTEST:"暫定回測",PROVISIONAL_PASSED:"暫定通過",PROVISIONAL_FAILED_GATE:"未通過暫定門檻",BREAKOUT_READY:"高品質放量突破，可以進場",PULLBACK_READY:"健康回踩確認，可以進場",WAIT_PULLBACK:"趨勢良好，等待健康回踩",OVEREXTENDED:"趨勢良好但過度延伸，至少等待三個交易日",NO_SETUP:"尚無確認的進場型態",BLOCKED_REGIME:"市場狀態不允許新買進",BLOCKED_DATA:"缺少市場基準或廣度資料",MARKET_CONTEXT_MISSING:"市場基準或廣度無法使用",MARKET_RISK_OFF:"避險狀態阻止新買進",PRICE_OVEREXTENDED:"價格延伸或異常波動冷卻期阻止買進",WAITING_FOR_PULLBACK:"等待健康回踩",NO_ENTRY_SETUP:"沒有突破或回踩確認",STOP_DISTANCE_OUT_OF_RANGE:"停損距離必須在 1.25%–8%",RISK_ON:"積極",NEUTRAL:"中性"},
  ja:{ WATCH:"監視",PUBLIC_DATA_SHADOW:"公開データのシャドー",NON_GENUINE_OHLCV:"実測OHLCVなし",SECTOR_UNKNOWN:"業種不明",SOURCE_CONFLICT:"情報源の差が1%超",CORPORATE_ACTION_ANOMALY:"企業行動の異常",ETF_STRUCTURE_EXCLUDED:"ETF構造が不適格",PRICE_NOT_ABOVE_MA_SET:"価格が20/50/200日線を上回っていません",LONG_TREND_NOT_RISING:"50/200日トレンドが上昇していません",MOMENTUM_NOT_POSITIVE:"3/6か月リターンが共にプラスではありません",RELATIVE_STRENGTH_BELOW_70:"相対強度70未満",VOLUME_CONFIRMATION_PENDING:"出来高確認待ち",RISK_OFF:"市場はリスクオフ",ETF_STRUCTURE_INCOMPLETE:"ETF構造データ不足",DAILY_SELECTION_CAP:"日次3+1上限",SITE_FALLBACK_WATCH_ONLY:"サイト予備スキャンは監視のみ",PROVISIONAL_BACKTEST:"暫定バックテスト",PROVISIONAL_PASSED:"暫定合格",PROVISIONAL_FAILED_GATE:"暫定基準不合格",BREAKOUT_READY:"高品質な出来高ブレイクでエントリー可能",PULLBACK_READY:"健全な押し目を確認しエントリー可能",WAIT_PULLBACK:"良好なトレンド、押し目待ち",OVEREXTENDED:"過度に上昇、最低3取引日待機",NO_SETUP:"確認済みのエントリー形状なし",BLOCKED_REGIME:"市場状態が新規買いを許可していません",BLOCKED_DATA:"指数または市場幅データ不足",MARKET_CONTEXT_MISSING:"指数または市場幅を取得できません",MARKET_RISK_OFF:"リスクオフで新規買い停止",PRICE_OVEREXTENDED:"価格乖離または急変の冷却期間",WAITING_FOR_PULLBACK:"健全な押し目待ち",NO_ENTRY_SETUP:"ブレイクまたは押し目確認なし",STOP_DISTANCE_OUT_OF_RANGE:"損切り幅は1.25%～8%",RISK_ON:"リスクオン",NEUTRAL:"中立"},
  ko:{ WATCH:"관찰",PUBLIC_DATA_SHADOW:"공개 데이터 섀도",NON_GENUINE_OHLCV:"실제 OHLCV 없음",SECTOR_UNKNOWN:"업종 미분류",SOURCE_CONFLICT:"출처 차이 1% 초과",CORPORATE_ACTION_ANOMALY:"기업행동 이상",ETF_STRUCTURE_EXCLUDED:"ETF 구조 부적격",PRICE_NOT_ABOVE_MA_SET:"가격이 20/50/200일선 위가 아님",LONG_TREND_NOT_RISING:"50/200일 추세 미상승",MOMENTUM_NOT_POSITIVE:"3/6개월 수익률이 모두 양수가 아님",RELATIVE_STRENGTH_BELOW_70:"상대강도 70 미만",VOLUME_CONFIRMATION_PENDING:"거래량 확인 대기",RISK_OFF:"시장 위험회피 상태",ETF_STRUCTURE_INCOMPLETE:"ETF 구조 데이터 부족",DAILY_SELECTION_CAP:"일일 3+1 상한",SITE_FALLBACK_WATCH_ONLY:"사이트 예비 스캔은 관찰 전용",PROVISIONAL_BACKTEST:"잠정 백테스트",PROVISIONAL_PASSED:"잠정 통과",PROVISIONAL_FAILED_GATE:"잠정 기준 실패",BREAKOUT_READY:"고품질 거래량 돌파, 진입 가능",PULLBACK_READY:"건전한 눌림 확인, 진입 가능",WAIT_PULLBACK:"추세 양호, 눌림 대기",OVEREXTENDED:"과도한 상승, 최소 3거래일 대기",NO_SETUP:"확인된 진입 패턴 없음",BLOCKED_REGIME:"시장 상태가 신규 매수를 허용하지 않음",BLOCKED_DATA:"시장 지수 또는 시장 폭 데이터 부족",MARKET_CONTEXT_MISSING:"시장 지수 또는 시장 폭 없음",MARKET_RISK_OFF:"위험회피 상태로 신규 매수 차단",PRICE_OVEREXTENDED:"가격 확장 또는 급변 냉각 기간",WAITING_FOR_PULLBACK:"건전한 눌림 대기",NO_ENTRY_SETUP:"돌파 또는 눌림 확인 없음",STOP_DISTANCE_OUT_OF_RANGE:"손절 거리는 1.25%–8%여야 함",RISK_ON:"위험선호",NEUTRAL:"중립"},
};

const entryDetailCodes:Record<Locale,Record<string,string>> = {
  en:{ BREAKOUT_VOLUME_INSUFFICIENT:"Breakout volume is below 1.5× the 20-day median" },
  "zh-CN":{ BREAKOUT_VOLUME_INSUFFICIENT:"突破量能不足 20 日中位量的 1.5 倍" },
  "zh-TW":{ BREAKOUT_VOLUME_INSUFFICIENT:"突破量能未達 20 日中位量的 1.5 倍" },
  ja:{ BREAKOUT_VOLUME_INSUFFICIENT:"ブレイク時の出来高が20日中央値の1.5倍未満" },
  ko:{ BREAKOUT_VOLUME_INSUFFICIENT:"돌파 거래량이 20일 중앙값의 1.5배 미만" },
};
for (const locale of Object.keys(entryDetailCodes) as Locale[]) Object.assign(v2Codes[locale],entryDetailCodes[locale]);

const holdingCodes:Record<Locale,Record<string,string>> = {
  en:{ REVIEW:"Review data",HOLDING_QUOTE_STALE:"Latest quote is stale or unavailable",HOLDING_ANALYSIS_MISSING:"No active v2 analysis for this holding",HOLDING_ANALYSIS_STALE:"The active model analysis is too old",HOLDING_DATA_CONFLICT:"A source or corporate-action conflict requires review",HOLDING_SIGNAL_EXIT:"The active signal calls for exit",HOLDING_STOP_TRIGGERED:"Current price reached the ATR stop",HOLDING_INVALIDATION_TRIGGERED:"The structural invalidation level was breached",HOLDING_SCORE_BELOW_50_TWO_DAYS:"Score stayed below 50 for two sessions",HOLDING_SIGNAL_REDUCE:"The active signal calls for reduction",HOLDING_SCORE_BELOW_55_TWO_DAYS:"Score stayed below 55 for two sessions",HOLDING_RISK_OFF:"The market regime is risk-off",HOLDING_TREND_FAILED:"Long-term trend conditions failed",HOLDING_TARGET1_REACHED:"The first profit target was reached",HOLDING_TARGET2_REACHED:"The second profit target was reached",HOLDING_POSITION_LIMIT_EXCEEDED:"Single-position exposure exceeds the selected plan",HOLDING_MARKET_LIMIT_EXCEEDED:"Market exposure exceeds the selected plan",HOLDING_SECTOR_LIMIT_EXCEEDED:"Sector exposure exceeds the selected plan",HOLDING_SIGNAL_WATCH:"The latest signal is WATCH; monitor rather than add",HOLDING_PLAN_VALID:"Trend and risk guardrails remain valid",HOLDING_BELOW_FIRST_TARGET:"Price remains below the first profit target"},
  "zh-CN":{ REVIEW:"检查数据",HOLDING_QUOTE_STALE:"最新行情已过期或不可用",HOLDING_ANALYSIS_MISSING:"该持仓没有已启用的 v2 分析",HOLDING_ANALYSIS_STALE:"当前模型分析时间过久",HOLDING_DATA_CONFLICT:"数据源或公司行动冲突需要人工检查",HOLDING_SIGNAL_EXIT:"当前信号要求退出",HOLDING_STOP_TRIGGERED:"现价已触及 ATR 止损",HOLDING_INVALIDATION_TRIGGERED:"已跌破结构失效点",HOLDING_SCORE_BELOW_50_TWO_DAYS:"评分连续两日低于 50",HOLDING_SIGNAL_REDUCE:"当前信号要求减仓",HOLDING_SCORE_BELOW_55_TWO_DAYS:"评分连续两日低于 55",HOLDING_RISK_OFF:"市场处于避险状态",HOLDING_TREND_FAILED:"长期趋势条件失效",HOLDING_TARGET1_REACHED:"已达到第一分批目标",HOLDING_TARGET2_REACHED:"已达到第二分批目标",HOLDING_POSITION_LIMIT_EXCEEDED:"单股占比超过所选计划上限",HOLDING_MARKET_LIMIT_EXCEEDED:"市场占比超过所选计划上限",HOLDING_SECTOR_LIMIT_EXCEEDED:"行业占比超过所选计划上限",HOLDING_SIGNAL_WATCH:"最新信号为观察，不宜继续加仓",HOLDING_PLAN_VALID:"趋势和风险保护仍有效",HOLDING_BELOW_FIRST_TARGET:"价格尚未达到第一获利目标"},
  "zh-TW":{ REVIEW:"檢查資料",HOLDING_QUOTE_STALE:"最新行情已過期或無法使用",HOLDING_ANALYSIS_MISSING:"該持倉沒有已啟用的 v2 分析",HOLDING_ANALYSIS_STALE:"目前模型分析時間過久",HOLDING_DATA_CONFLICT:"資料源或公司行動衝突需要人工檢查",HOLDING_SIGNAL_EXIT:"目前訊號要求退出",HOLDING_STOP_TRIGGERED:"現價已觸及 ATR 停損",HOLDING_INVALIDATION_TRIGGERED:"已跌破結構失效點",HOLDING_SCORE_BELOW_50_TWO_DAYS:"評分連續兩日低於 50",HOLDING_SIGNAL_REDUCE:"目前訊號要求減碼",HOLDING_SCORE_BELOW_55_TWO_DAYS:"評分連續兩日低於 55",HOLDING_RISK_OFF:"市場處於避險狀態",HOLDING_TREND_FAILED:"長期趨勢條件失效",HOLDING_TARGET1_REACHED:"已達到第一分批目標",HOLDING_TARGET2_REACHED:"已達到第二分批目標",HOLDING_POSITION_LIMIT_EXCEEDED:"單檔占比超過所選計畫上限",HOLDING_MARKET_LIMIT_EXCEEDED:"市場占比超過所選計畫上限",HOLDING_SECTOR_LIMIT_EXCEEDED:"產業占比超過所選計畫上限",HOLDING_SIGNAL_WATCH:"最新訊號為觀察，不宜繼續加碼",HOLDING_PLAN_VALID:"趨勢與風險保護仍有效",HOLDING_BELOW_FIRST_TARGET:"價格尚未達到第一獲利目標"},
  ja:{ REVIEW:"データ確認",HOLDING_QUOTE_STALE:"最新価格が古いか取得できません",HOLDING_ANALYSIS_MISSING:"この保有銘柄に有効な v2 分析がありません",HOLDING_ANALYSIS_STALE:"モデル分析が古すぎます",HOLDING_DATA_CONFLICT:"情報源または企業行動の競合を確認してください",HOLDING_SIGNAL_EXIT:"有効シグナルは退出を示しています",HOLDING_STOP_TRIGGERED:"現在値が ATR 損切りに到達しました",HOLDING_INVALIDATION_TRIGGERED:"構造的な無効化水準を下回りました",HOLDING_SCORE_BELOW_50_TWO_DAYS:"スコアが2日連続50未満です",HOLDING_SIGNAL_REDUCE:"有効シグナルは縮小を示しています",HOLDING_SCORE_BELOW_55_TWO_DAYS:"スコアが2日連続55未満です",HOLDING_RISK_OFF:"市場はリスクオフです",HOLDING_TREND_FAILED:"長期トレンド条件が崩れました",HOLDING_TARGET1_REACHED:"第1利益目標に到達しました",HOLDING_TARGET2_REACHED:"第2利益目標に到達しました",HOLDING_POSITION_LIMIT_EXCEEDED:"銘柄比率が選択プランの上限超過です",HOLDING_MARKET_LIMIT_EXCEEDED:"市場比率が選択プランの上限超過です",HOLDING_SECTOR_LIMIT_EXCEEDED:"業種比率が選択プランの上限超過です",HOLDING_SIGNAL_WATCH:"最新シグナルは監視で、追加購入には不向きです",HOLDING_PLAN_VALID:"トレンドとリスク条件は有効です",HOLDING_BELOW_FIRST_TARGET:"価格は第1利益目標未満です"},
  ko:{ REVIEW:"데이터 확인",HOLDING_QUOTE_STALE:"최신 시세가 오래되었거나 없습니다",HOLDING_ANALYSIS_MISSING:"이 보유 종목에 활성 v2 분석이 없습니다",HOLDING_ANALYSIS_STALE:"현재 모델 분석이 너무 오래되었습니다",HOLDING_DATA_CONFLICT:"출처 또는 기업행동 충돌을 확인해야 합니다",HOLDING_SIGNAL_EXIT:"활성 신호가 청산을 지시합니다",HOLDING_STOP_TRIGGERED:"현재가가 ATR 손절선에 도달했습니다",HOLDING_INVALIDATION_TRIGGERED:"구조 무효화 가격을 하회했습니다",HOLDING_SCORE_BELOW_50_TWO_DAYS:"점수가 이틀 연속 50 미만입니다",HOLDING_SIGNAL_REDUCE:"활성 신호가 축소를 지시합니다",HOLDING_SCORE_BELOW_55_TWO_DAYS:"점수가 이틀 연속 55 미만입니다",HOLDING_RISK_OFF:"시장이 위험회피 상태입니다",HOLDING_TREND_FAILED:"장기 추세 조건이 무너졌습니다",HOLDING_TARGET1_REACHED:"1차 수익 목표에 도달했습니다",HOLDING_TARGET2_REACHED:"2차 수익 목표에 도달했습니다",HOLDING_POSITION_LIMIT_EXCEEDED:"종목 비중이 선택 계획의 한도를 초과합니다",HOLDING_MARKET_LIMIT_EXCEEDED:"시장 비중이 선택 계획의 한도를 초과합니다",HOLDING_SECTOR_LIMIT_EXCEEDED:"업종 비중이 선택 계획의 한도를 초과합니다",HOLDING_SIGNAL_WATCH:"최신 신호는 관찰이며 추가 매수에 적합하지 않습니다",HOLDING_PLAN_VALID:"추세와 위험 조건이 유효합니다",HOLDING_BELOW_FIRST_TARGET:"가격이 1차 수익 목표보다 낮습니다"},
};
for (const locale of Object.keys(holdingCodes) as Locale[]) Object.assign(v2Codes[locale],holdingCodes[locale]);

const profileCodes:Record<Locale,Record<string,string>>={
  en:{TREND:"Trend",BALANCED:"Balanced",DEFENSIVE_PULLBACK:"Defensive pullback",CONSERVATIVE:"Conservative",CORE:"Standard",VOLATILITY_ADJUSTED:"Volatility adjusted",PROFILE_TREND:"Trend profile",PROFILE_BALANCED:"Balanced profile",PROFILE_DEFENSIVE_PULLBACK:"Defensive pullback profile",GATES_CONSERVATIVE:"Conservative gates",GATES_CORE:"Standard gates",GATES_VOLATILITY_ADJUSTED:"Volatility-adjusted gates",HOLDING_MINIMUM_LOT_CONCENTRATION:"Concentration is retained under the audited minimum-lot exception"},
  "zh-CN":{TREND:"趋势型",BALANCED:"均衡型",DEFENSIVE_PULLBACK:"防守回踩型",CONSERVATIVE:"保守",CORE:"标准",VOLATILITY_ADJUSTED:"波动调整",PROFILE_TREND:"趋势型配置",PROFILE_BALANCED:"均衡型配置",PROFILE_DEFENSIVE_PULLBACK:"防守回踩型配置",GATES_CONSERVATIVE:"保守门槛",GATES_CORE:"标准门槛",GATES_VOLATILITY_ADJUSTED:"波动调整门槛",HOLDING_MINIMUM_LOT_CONCENTRATION:"该集中持仓由可审计的首次整手例外保留"},
  "zh-TW":{TREND:"趨勢型",BALANCED:"均衡型",DEFENSIVE_PULLBACK:"防守回踩型",CONSERVATIVE:"保守",CORE:"標準",VOLATILITY_ADJUSTED:"波動調整",PROFILE_TREND:"趨勢型配置",PROFILE_BALANCED:"均衡型配置",PROFILE_DEFENSIVE_PULLBACK:"防守回踩型配置",GATES_CONSERVATIVE:"保守門檻",GATES_CORE:"標準門檻",GATES_VOLATILITY_ADJUSTED:"波動調整門檻",HOLDING_MINIMUM_LOT_CONCENTRATION:"此集中持倉由可稽核的首次整手例外保留"},
  ja:{TREND:"トレンド型",BALANCED:"バランス型",DEFENSIVE_PULLBACK:"守備的押し目型",CONSERVATIVE:"保守",CORE:"標準",VOLATILITY_ADJUSTED:"変動調整",PROFILE_TREND:"トレンド設定",PROFILE_BALANCED:"バランス設定",PROFILE_DEFENSIVE_PULLBACK:"守備的押し目設定",GATES_CONSERVATIVE:"保守的基準",GATES_CORE:"標準基準",GATES_VOLATILITY_ADJUSTED:"変動調整基準",HOLDING_MINIMUM_LOT_CONCENTRATION:"監査可能な初回最低単位の例外による集中保有です"},
  ko:{TREND:"추세형",BALANCED:"균형형",DEFENSIVE_PULLBACK:"방어 눌림형",CONSERVATIVE:"보수",CORE:"표준",VOLATILITY_ADJUSTED:"변동성 조정",PROFILE_TREND:"추세형 구성",PROFILE_BALANCED:"균형형 구성",PROFILE_DEFENSIVE_PULLBACK:"방어 눌림형 구성",GATES_CONSERVATIVE:"보수 기준",GATES_CORE:"표준 기준",GATES_VOLATILITY_ADJUSTED:"변동성 조정 기준",HOLDING_MINIMUM_LOT_CONCENTRATION:"감사 가능한 첫 최소 단위 예외로 집중 보유를 유지합니다"},
};
for(const locale of Object.keys(profileCodes) as Locale[])Object.assign(v2Codes[locale],profileCodes[locale]);

export function riskPlanName(locale:Locale, id:unknown) {
  const key:CopyKey = id === "growth" ? "growth" : id === "balanced" ? "balanced" : "capitalFirst";
  return tx(locale,key);
}

const errorKeys:Record<string,CopyKey> = {
  SIGN_IN_REQUIRED:"errorSignIn", SERVICE_UNAVAILABLE:"errorService", INVALID_ORDER:"errorInvalidOrder", SETUP_REQUIRED:"errorSetup", NO_QUOTE:"errorNoQuote", MARKET_QUANTITY_RULE:"errorMarketQuantity", STALE_QUOTE:"errorStaleQuote", PRICE_OUTSIDE_ENTRY_ZONE:"errorReanalysisRequired", DRAWDOWN_BREAKER:"errorDrawdown", CN_T_PLUS_ONE:"errorT1", POSITION_LIMIT:"errorPosition", MARKET_LIMIT:"errorMarket", SECTOR_LIMIT:"errorSector", INSUFFICIENT_CASH:"errorCash", PORTFOLIO_UNAVAILABLE:"errorPortfolio", PAPER_ORDER_FAILED:"errorOrder",
  PAPER_CAPITAL_REQUIRED:"errorCapitalRequired", CAPITAL_REDUCTION_BLOCKED:"errorCapitalReduction", BASE_CURRENCY_LOCKED:"errorCurrencyLocked", SETTINGS_SAVE_FAILED:"errorSettings",
  MARKET_NOT_ENABLED:"errorMarketDisabled", TRADE_RISK_LIMIT:"errorTradeRisk", RISK_POLICY_INVALID:"errorRiskPolicy",
  HOLDING_QUOTE_REFRESH_FAILED:"errorQuoteRefresh",
};

export function apiErrorText(locale:Locale, payload:{errorCode?:string;errorParams?:Params}|null|undefined, fallback:CopyKey="errorGeneric") {
  const key = payload?.errorCode ? errorKeys[payload.errorCode] : undefined;
  const params = { ...payload?.errorParams };
  if (params.plan) params.plan = riskPlanName(locale,params.plan);
  return tx(locale,key ?? fallback,params);
}
